import type { MarketAnalysisSummary } from "./types";

export function buildAnalysisMdx(summary: MarketAnalysisSummary): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push(`title: "Market Analysis: ${summary.date}"`);
  lines.push(`date: ${summary.date}`);
  lines.push(`generatedAt: "${summary.generatedAt}"`);
  lines.push("---");
  lines.push("");
  lines.push("{/* Generated by bun run market:analyze. Do not edit by hand. */}");
  lines.push("");
  lines.push("<AnalysisSummary />");
  lines.push("");
  lines.push("## Universe");
  lines.push("");
  lines.push(`Symbols: ${summary.symbols.join(", ")}`);
  lines.push("");
  lines.push(`Intervals: ${summary.intervals.join(", ")}`);
  lines.push("");

  if (summary.missingSymbols.length > 0) {
    lines.push(`Missing symbols: ${summary.missingSymbols.join(", ")}`);
    lines.push("");
  }

  for (const symbol of summary.symbols) {
    const byInterval = summary.series[symbol];
    if (!byInterval) {
      continue;
    }

    lines.push(`## ${symbol}`);
    lines.push("");

    const missingIntervals = summary.intervals.filter((interval) => !byInterval[interval]);
    if (missingIntervals.length > 0) {
      lines.push(`Missing intervals: ${missingIntervals.join(", ")}`);
      lines.push("");
    }

    for (const interval of summary.intervals) {
      if (!byInterval[interval]) {
        continue;
      }

      lines.push(`### ${interval}`);
      lines.push("");
      lines.push(`<AnalysisSeries symbol="${symbol}" interval="${interval}" />`);
      lines.push("");
    }
  }

  return `${lines.join("\n")}\n`;
}
